Refactor indexer to add more chains
Signed-off-by: Borg <brussel17891@gmail.com>

diff --git a/.github/workflows/github-pages.yaml b/.github/workflows/github-pages.yaml
--- a/.github/workflows/github-pages.yaml
+++ b/.github/workflows/github-pages.yaml
@@ -4,9 +4,9 @@ on:
   # Runs on pushes targeting the default branch
   push:
     branches: [main]
-  schedule:
-    # Runs at the 27th minute of every hour
-    - cron: "27 * * * *"
+      #  schedule:
+      #    # Runs at the 27th minute of every hour
+      #    - cron: "27 * * * *"
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
@@ -71,11 +71,23 @@ jobs:
           pages_url=$(gh api "repos/$GITHUB_REPOSITORY/pages" --jq '.html_url')
           echo "Github pages URL: $pages_url"
           (
-          mkdir -pv ./out/indexing/avalanche-fuji
-          wget -O ./out/indexing/avalanche-fuji/index.db ${pages_url}/indexing/avalanche-fuji/index.db || echo "Failed to download index checkpoint"
+          mkdir -pv ./out/indexing/ethereum
+          wget -O ./out/indexing/ethereum/index.db ${pages_url}/indexing/ethereum/index.db || echo "Failed to download index checkpoint"
           node scripts/esbuild.js
-          node ./indexer.js --chain "Avalanche Fuji" ./out/indexing/avalanche-fuji
+          node ./indexer.js --chain "Ethereum" ./out/indexing/ethereum
           ) &
+          # (
+          # mkdir -pv ./out/indexing/arbitrum-one
+          # wget -O ./out/indexing/arbitrum-one/index.db ${pages_url}/indexing/arbitrum-one/index.db || echo "Failed to download index checkpoint"
+          # node scripts/esbuild.js
+          # node ./indexer.js --chain "Arbitrum One" ./out/indexing/arbitrum-one
+          # ) &
+          # (
+          # mkdir -pv ./out/indexing/avalanche-fuji
+          # wget -O ./out/indexing/avalanche-fuji/index.db ${pages_url}/indexing/avalanche-fuji/index.db || echo "Failed to download index checkpoint"
+          # node scripts/esbuild.js
+          # node ./indexer.js --chain "Avalanche Fuji" ./out/indexing/avalanche-fuji
+          # ) &
           wait
           echo "All indexing jobs are done"
       - name: Upload artifact
